name: "ShellScript Formatter"

author: "ryohidaka"

description: "A GitHub Action that formats shell scripts using shfmt."

branding:
  color: green
  icon: send

inputs:
  path:
    description: "Directory path to format shell scripts."
    required: false
    default: "."

runs:
  using: "composite"
  steps:
    - name: Install shfmt
      run: ./scripts/install-shfmt.sh
      shell: bash
