name: "ShellScript Formatter"

author: "ryohidaka"

description: "A GitHub Action that formats shell scripts using shfmt."

branding:
  color: green
  icon: send

runs:
  using: "composite"
  steps:
    - name: Install shfmt
      run: ./scripts/install-shfmt.sh
      shell: bash
