name: "ShellScript Formatter"

author: "ryohidaka"

description: "A GitHub Action that formats shell scripts using shfmt."

branding:
  color: yellow
  icon: check-circle

inputs:
  path:
    description: "Directory path to format shell scripts."
    required: false
    default: "."

  # shfmt options
  indent:
    description: "Set the indentation level for shfmt. Default is 4."
    required: false
    default: "4"

  # commit options
  commit-user-name:
    required: false
    default: "GitHub Actions"
    description: "Commit username. Defaults to 'GitHub Actions'."

  commit-user-email:
    required: false
    default: "actions@github.com"
    description: "Commit email. Defaults to 'actions@github.com'."

  commit-message:
    required: false
    default: "chore: Format ShellScripts"
    description: "Commit message. Defaults to 'chore: Format ShellScripts'."

  dry-run:
    description: "If true, the commit and push steps will be skipped."
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set GitHub Path
      run: echo "GITHUB_ACTION_PATH=${GITHUB_ACTION_PATH}" >> $GITHUB_ENV
      shell: bash

    - name: Install shfmt
      run: $GITHUB_ACTION_PATH/scripts/install-shfmt.sh
      shell: bash

    - name: Run shfmt
      run: |
        $GITHUB_ACTION_PATH/scripts/run-shfmt.sh \
          ${{ inputs.path }} \
          ${{ inputs.indent }}
      shell: bash

    - name: Commit and Push
      if: ${{ inputs.dry-run == 'false' }}
      run: |
        $GITHUB_ACTION_PATH/scripts/commit-push.sh \
          "${{ inputs.path }}" \
          "${{ inputs.commit-user-name }}" \
          "${{ inputs.commit-user-email }}" \
          "${{ inputs.commit-message }}"
      shell: bash
