name: "ShellScript Formatter"

author: "ryohidaka"

description: "A GitHub Action that formats shell scripts using shfmt."

branding:
  color: yellow
  icon: check-circle

inputs:
  path:
    description: "Directory path to format shell scripts."
    required: false
    default: "."

  # shfmt options
  indent:
    description: "Set the indentation level for shfmt. Default is 4."
    required: false
    default: "4"

  # commit options
  commit-user-name:
    required: false
    default: "github-actions[bot]"
    description: "Commit username. Defaults to 'github-actions[bot]'."

  commit-user-email:
    required: false
    default: "41898282+github-actions[bot]@users.noreply.github.com"
    description: "Commit email. Defaults to '41898282+github-actions[bot]@users.noreply.github.com'."

  commit-message:
    required: false
    default: "chore: Format ShellScripts"
    description: "Commit message. Defaults to 'chore: Format ShellScripts'."

  dry-run:
    description: "If true, the commit and push steps will be skipped."
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set GitHub Path
      run: echo "GITHUB_ACTION_PATH=${GITHUB_ACTION_PATH}" >> $GITHUB_ENV
      shell: bash

    - name: Install shfmt
      run: $GITHUB_ACTION_PATH/scripts/install-shfmt.sh
      shell: bash

    - name: Run shfmt
      run: |
        $GITHUB_ACTION_PATH/scripts/run-shfmt.sh \
          ${{ inputs.path }} \
          ${{ inputs.indent }}
      shell: bash

    - name: Commit and Push
      uses: ryohidaka/action-commit-push@v0.6.0
      with:
        files: "${{ inputs.path }}"
        commit-user-name: "${{ inputs.commit-user-name }}"
        commit-user-email: "${{ inputs.commit-user-email }}"
        commit-message: "${{ inputs.commit-message }}"
        dry-run: ${{ inputs.dry-run }}
