name: "Test"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: "./"
        with:
          path: "./sample"
          dry-run: true

      - name: Check diff
        run: git diff sample
